# Configuration file for Travis continuous integration.
# See https://travis-ci.org/julianhyde/pentaho-aggdesigner
#
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
branches:
  only:
    - master
    - maven
script:
  mvn package
git:
  depth: 10000
sudo: false
cache:
  directories:
    - $HOME/.m2
# End .travis.yml
